//????????.???????
//??????
handlers= java.util.logging.ConsoleHandler,java.util.logging.FileHandler

//???????????????INFO
.level= INFO

//com.peanut????????????????
com.peanut.handlers = java.util.logging.ConsoleHandler
com.peanut.level = ALL

com.peanut.useParentHandlers = false

java.util.logging.FileHandler.pattern = logs/java%u.log
java.util.logging.FileHandler.limit = 50000
java.util.logging.FileHandler.count = 1
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.encoding = UTF-8
java.util.logging.FileHandler.append = true

java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.encoding = UTF-8
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format = %4$s: %5$s [%1$tc]%n

