# ????? logger ??????
logging.level.com.itheima=trace
# ???????????
logging.pattern.console=[%-5level] %d{yyyy-MM-dd HH:mm:ss} %c [%thread]===== %msg %n
#?????????????
logging.file=/logs/springboot.log
#?????????????????? spring.log
logging.file.path=/logs/springboot/
#??????????
logging.pattern.file=[%-5level] %d{yyyy-MM-dd HH:mm:ss} %c [%thread]===== %msg %n